# Generated by Django 2.2.6 on 2019-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=100),
        ),
    ]
