# Generated by Django 2.2.6 on 2019-10-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0002_auto_20191023_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.TextField(max_length=100),
        ),
    ]
